version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: anime_parsing_app
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - HOST=0.0.0.0
      - KODIK_PROXY=
    volumes:
      - ./data:/app/data
