"""Watch Order & Franchise Chronological Roadmap Engine.

Provides clear, interactive step-by-step pathways explaining how to watch
complex anime universes (chronological vs release order, canon status, OVA importance).
"""
from __future__ import annotations

WATCH_ORDERS: dict[str, dict] = {
    "steins-gate": {
        "title": "Хронология вселенной Врат Штейна (Steins;Gate)",
        "recommended_order": "release",
        "description": "Сложная временная линия с развилками. Рекомендуется смотреть в порядке выхода, либо в хронологическом порядке для глубокого погружения.",
        "steps": [
            {
                "step": 1,
                "title": "Врата Штейна (Сезон 1, серии 1–22)",
                "type": "anime",
                "episodes": "22 эп.",
                "canon_level": "essential",
                "canon_label": "🟢 Главный канон",
                "note": "Основная мировая линия α (Альфа). Остановитесь на 22 серии.",
            },
            {
                "step": 2,
                "title": "Врата Штейна: Эпизод 23β (Развилка)",
                "type": "special",
                "episodes": "1 эп. (спешл)",
                "canon_level": "essential",
                "canon_label": "🟢 Ключевая развилка",
                "note": "Альтернативная концовка 23 серии, ведущая к линии Врат Штейна 0.",
            },
            {
                "step": 3,
                "title": "Врата Штейна 0 (Steins;Gate 0)",
                "type": "anime",
                "episodes": "23 эп.",
                "canon_level": "essential",
                "canon_label": "🟢 Главный канон (линия β)",
                "note": "История страданий Окабэ, сделавшая возможным спасение в оригинале.",
            },
            {
                "step": 4,
                "title": "Врата Штейна (Сезон 1, серии 23–24)",
                "type": "anime",
                "episodes": "2 эп.",
                "canon_level": "essential",
                "canon_label": "🟢 Истинный финал",
                "note": "Возвращение к оригинальному финалу и выход на линию Врат Штейна.",
            },
            {
                "step": 5,
                "title": "OVA: Эгоистичная пориомания (Серия 25)",
                "type": "ova",
                "episodes": "1 эп.",
                "canon_level": "recommended",
                "canon_label": "🟡 Рекомендуется",
                "note": "Спешл-эпилог в Америке.",
            },
            {
                "step": 6,
                "title": "Фильм: Зона загрузки дежавю",
                "type": "movie",
                "episodes": "Фильм (90 мин)",
                "canon_level": "optional",
                "canon_label": "⚪ По желанию (полуканон)",
                "note": "Романтическое продолжение о Курису, спасающей Окабэ из таймлайна.",
            },
        ],
    },
    "attack-on-titan": {
        "title": "Хронология Атаки Титанов (Shingeki no Kyojin)",
        "recommended_order": "chronological",
        "description": "Эпическая сквозная сага. Важно не пропустить канонические OVA про прошлое Леви и дневник Ильзе.",
        "steps": [
            {
                "step": 1,
                "title": "Атака Титанов (Сезон 1)",
                "type": "anime",
                "episodes": "25 эп.",
                "canon_level": "essential",
                "canon_label": "🟢 Главный канон",
                "note": "Падение стены Мария и вступление в Разведкорпус.",
            },
            {
                "step": 2,
                "title": "OVA: Дневник Ильзе + Выбор без сожалений (Леви)",
                "type": "ova",
                "episodes": "3 эп.",
                "canon_level": "essential",
                "canon_label": "🟢 Обязательный канон",
                "note": "Раскрывает тайну говорящего титана и трагическое прошлое капрала Леви.",
            },
            {
                "step": 3,
                "title": "Атака Титанов (Сезон 2)",
                "type": "anime",
                "episodes": "12 эп.",
                "canon_level": "essential",
                "canon_label": "🟢 Главный канон",
                "note": "Битва в замке Утгард и тайна Звероподобного.",
            },
            {
                "step": 4,
                "title": "Атака Титанов (Сезон 3: Части 1 и 2)",
                "type": "anime",
                "episodes": "22 эп.",
                "canon_level": "essential",
                "canon_label": "🟢 Главный канон",
                "note": "Политическая арка революции и битва за возвращение стены Мария (Подвал).",
            },
            {
                "step": 5,
                "title": "Атака Титанов: Финал (The Final Season, Части 1, 2, 3 и Спешлы)",
                "type": "anime",
                "episodes": "30 эп.",
                "canon_level": "essential",
                "canon_label": "🟢 Кульминация и Финал",
                "note": "Война с Марли, Гул Земли и грандиозный финал истории Эрена.",
            },
        ],
    },
    "cowboy-bebop": {
        "title": "Порядок просмотра Ковбоя Бибопа",
        "recommended_order": "chronological",
        "description": "Основной сериал и канонический полнометражный фильм.",
        "steps": [
            {
                "step": 1,
                "title": "Ковбой Бибоп (Серии 1–22)",
                "type": "anime",
                "episodes": "22 эп.",
                "canon_level": "essential",
                "canon_label": "🟢 Главный канон",
                "note": "Приключения команды Бибопа на просторах Солнечной системы.",
            },
            {
                "step": 2,
                "title": "Фильм: Достучаться до небес (Knockin' on Heaven's Door)",
                "type": "movie",
                "episodes": "Фильм (115 мин)",
                "canon_level": "essential",
                "canon_label": "🟢 Канонический фильм",
                "note": "События происходят на Марсе прямо перед Хэллоуином между 22 и 23 сериями.",
            },
            {
                "step": 3,
                "title": "Ковбой Бибоп (Серии 23–26: Финал)",
                "type": "anime",
                "episodes": "4 эп.",
                "canon_level": "essential",
                "canon_label": "🟢 Финал истории",
                "note": "Развязка прошлого Спайка и схватка с Вишезом (The Real Folk Blues).",
            },
        ],
    },
    "fma-brotherhood": {
        "title": "Стальной алхимик: Братство (Fullmetal Alchemist: Brotherhood)",
        "recommended_order": "release",
        "description": "Эталонная законченная экранизация манги Хирому Аракавы.",
        "steps": [
            {
                "step": 1,
                "title": "Стальной алхимик: Братство (64 серии)",
                "type": "anime",
                "episodes": "64 эп.",
                "canon_level": "essential",
                "canon_label": "🟢 100% Канон манги",
                "note": "Полная экранизация всех 27 томов манги от начала до счастливого финала.",
            },
            {
                "step": 2,
                "title": "OVA-коллекция (4 спешла)",
                "type": "ova",
                "episodes": "4 эп.",
                "canon_level": "recommended",
                "canon_label": "🟡 Рекомендуется",
                "note": "Предыстории Мустанга, Изуми Кёртис и слепого алхимика.",
            },
            {
                "step": 3,
                "title": "Фильм: Священная звезда Милоса",
                "type": "movie",
                "episodes": "Фильм (110 мин)",
                "canon_level": "optional",
                "canon_label": "⚪ По желанию (спин-офф)",
                "note": "Отдельное приключение братьев Элриков на границе Аместриса и Креты.",
            },
        ],
    },
    "nge": {
        "title": "Вселенная Евангелиона (Neon Genesis Evangelion)",
        "recommended_order": "release",
        "description": "Легендарная классика и ребилды Хидэаки Анно.",
        "steps": [
            {
                "step": 1,
                "title": "Евангелион (ТВ-сериал 1995 г., серии 1–24)",
                "type": "anime",
                "episodes": "24 эп.",
                "canon_level": "essential",
                "canon_label": "🟢 Оригинал",
                "note": "Классическая история Синдзи Икари и битв с Ангелами.",
            },
            {
                "step": 2,
                "title": "Конец Евангелиона (The End of Evangelion)",
                "type": "movie",
                "episodes": "Фильм (87 мин)",
                "canon_level": "essential",
                "canon_label": "🟢 Истинный финал",
                "note": "Альтернативный полномасштабный финал Третьего Удара взамен 25–26 серий.",
            },
            {
                "step": 3,
                "title": "Тетралогия Ребилдов: 1.11, 2.22, 3.33, 3.0+1.01",
                "type": "movie",
                "episodes": "4 фильма",
                "canon_level": "recommended",
                "canon_label": "🟡 Новая киновселенная",
                "note": "Современное переосмысление истории с новой концовкой «Прощайте, все Евангелионы».",
            },
        ],
    },
    "demon-slayer": {
        "title": "Хронология Клинка, рассекающего демонов (Kimetsu no Yaiba)",
        "recommended_order": "chronological",
        "description": "Последовательная экранизация манги студией Ufotable.",
        "steps": [
            {
                "step": 1,
                "title": "Клинок, рассекающий демонов (Сезон 1)",
                "type": "anime",
                "episodes": "26 эп.",
                "canon_level": "essential",
                "canon_label": "🟢 Главный канон",
                "note": "Обучение Тандзиро и битва на горе Натагумо с паучьей семьёй.",
            },
            {
                "step": 2,
                "title": "Поезд «Бесконечный» (Фильм или ТВ-версия из 7 серий)",
                "type": "movie",
                "episodes": "Фильм / 7 эп.",
                "canon_level": "essential",
                "canon_label": "🟢 Главный канон",
                "note": "Битва Столпа пламени Кёдзюро Рэнгоку против Третьей Высшей Луны Аказы.",
            },
            {
                "step": 3,
                "title": "Квартал красных фонарей (Сезон 2)",
                "type": "anime",
                "episodes": "11 эп.",
                "canon_level": "essential",
                "canon_label": "🟢 Главный канон",
                "note": "Битва со Столпом звука Тенгеном Узуем против Даки и Гютаро.",
            },
            {
                "step": 4,
                "title": "Деревня кузнецов (Сезон 3)",
                "type": "anime",
                "episodes": "11 эп.",
                "canon_level": "essential",
                "canon_label": "🟢 Главный канон",
                "note": "Арка кузнецов со Столпом любви Мицури и Столпом тумана Муитиро.",
            },
            {
                "step": 5,
                "title": "Тренировка столпов (Сезон 4)",
                "type": "anime",
                "episodes": "8 эп.",
                "canon_level": "essential",
                "canon_label": "🟢 Главный канон",
                "note": "Подготовка к финальной битве с Мудзаном.",
            },
            {
                "step": 6,
                "title": "Трилогия фильмов: Крепость бесконечности",
                "type": "movie",
                "episodes": "3 фильма (Анонс)",
                "canon_level": "essential",
                "canon_label": "🟢 Финал саги",
                "note": "Грандиозный финал манги в кинотеатрах.",
            },
        ],
    },
    "death-note": {
        "title": "Порядок просмотра Тетради Смерти",
        "recommended_order": "release",
        "description": "Законченный психологический шедевр.",
        "steps": [
            {
                "step": 1,
                "title": "Тетрадь Смерти (Сериал, 37 серий)",
                "type": "anime",
                "episodes": "37 эп.",
                "canon_level": "essential",
                "canon_label": "🟢 Главный канон",
                "note": "Полное противостояние Ягами Лайта и гениального детектива L.",
            },
            {
                "step": 2,
                "title": "Death Note: Relight (Глазами Бога / Наследники L)",
                "type": "special",
                "episodes": "2 спецвыпуска",
                "canon_level": "optional",
                "canon_label": "⚪ Рекап с новыми сценами",
                "note": "Взгляд на события глазами Рюка в мире синигами.",
            },
        ],
    },
    "one-punch-man": {
        "title": "Порядок просмотра Ванпанчмена",
        "recommended_order": "release",
        "description": "Приключения Сайтамы и Ассоциации героев.",
        "steps": [
            {
                "step": 1,
                "title": "Ванпанчмен (Сезон 1 от Madhouse) + 6 OVA",
                "type": "anime",
                "episodes": "12 эп. + 6 OVA",
                "canon_level": "essential",
                "canon_label": "🟢 Главный канон",
                "note": "Битва с Боросом и эталонная анимация.",
            },
            {
                "step": 2,
                "title": "Ванпанчмен (Сезон 2 от J.C.Staff) + 6 OVA",
                "type": "anime",
                "episodes": "12 эп. + 6 OVA",
                "canon_level": "essential",
                "canon_label": "🟢 Главный канон",
                "note": "Появление Гароу и турнир боевых искусств.",
            },
            {
                "step": 3,
                "title": "Ванпанчмен (Сезон 3: Ассоциация монстров)",
                "type": "anime",
                "episodes": "Анонсирован",
                "canon_level": "essential",
                "canon_label": "🟢 Продолжение",
                "note": "Масштабная война героев S-класса против монстров.",
            },
        ],
    },
}


def get_watch_order(title_key: str) -> dict | None:
    """Returns structured watch order roadmap for a given anime title."""
    return WATCH_ORDERS.get(title_key)
